"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "src/main/resources/assets/inventorysorter/lang"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  - source: /en_us.json
    translation: /%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        en-US: en_us
        ar: ar_ar
        be: be_by
        be-LATN: be_latn
        br-FR: br_fr
        da: da_dk
        de: de_de
        el: el_gr
        es-ES: es_es
        fi: fi_fi
        fr: fr_fr
        it: it_it
        ja: ja_jp
        "no": no_no
        pl: pl_pl
        pt-BR: pt_br
        ru: ru_ru
        sv-SE: sv_se
        tr: tr_tr
        uk: uk_ua
        zh-CN: zh_cn
        zh-HK: zh_hk
        zh-TW: zh_tw
